package RecordApp;

/**
* RecordApp/RecordHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Record.idl
* Saturday, October 27, 2018 4:00:10 PM EDT
*/

public final class RecordHolder implements org.omg.CORBA.portable.Streamable
{
  public RecordApp.Record value = null;

  public RecordHolder ()
  {
  }

  public RecordHolder (RecordApp.Record initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RecordApp.RecordHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RecordApp.RecordHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RecordApp.RecordHelper.type ();
  }

}
