package RecordApp.RecordPackage;

/**
* RecordApp/RecordPackage/ProjectHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from Record.idl
* Saturday, October 27, 2018 4:00:10 PM EDT
*/

public final class ProjectHolder implements org.omg.CORBA.portable.Streamable
{
  public RecordApp.RecordPackage.Project value = null;

  public ProjectHolder ()
  {
  }

  public ProjectHolder (RecordApp.RecordPackage.Project initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = RecordApp.RecordPackage.ProjectHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    RecordApp.RecordPackage.ProjectHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return RecordApp.RecordPackage.ProjectHelper.type ();
  }

}
